jwt:
  secretKey: ${JWT_SECRET}
logging:
  level:
    root:INFO
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
  sql:
    init:
      mode: always
