jwt:
  secretKey: ${JWT_SECRET}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: never